In [3]:
#Binarization
from sklearn.preprocessing import Binarizer
from pandas import read_csv
from numpy import set_printoptions
filename='/home/diwakar/Downloads/IITK ML Data/indians-diabetes.data.csv'
hnames=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=read_csv(filename,names=hnames)
array = dataframe.values
print(array)
#seprate array into input and output components
X= array[: ,0:8] #[row ,cols]
Y= array[: ,8]
binarizer=Binarizer(threshold=5)
binaryX=binarizer.fit_transform(X)
#summarize transformed data
print(binaryX[0:30, :])

[[  6.   148.    72.   ...   0.63  50.     1.  ]
 [  1.    85.    66.   ...   0.35  31.     0.  ]
 [  8.   183.    64.   ...   0.67  32.     1.  ]
 ...
 [  5.   121.    72.   ...   0.24  30.     0.  ]
 [  1.   126.    60.   ...   0.35  47.     1.  ]
 [  1.    93.    70.   ...   0.32  23.     0.  ]]
[[1. 1. 1. 1. 0. 1. 0. 1.]
 [0. 1. 1. 1. 0. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 0. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 0. 0. 0. 1.]
 [0. 1. 1. 0. 0. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 0. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [0. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0. 1.]
 [1. 1. 1. 0. 0. 1. 0. 1.]
 [1. 1. 1. 1. 0. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1.