In [2]:
#Feature Extraction with univariate stastical tests
#(chi-squired for classfication)
#chi2=(Observed Frequency-Expected Frequency) ** 2 / Expected Frequency
import pandas as pd
from numpy import set_printoptions

from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import warnings
warnings.filterwarnings("ignore")

#load data
filename='/home/diwakar/Downloads/IITK ML Data/indians-diabetes.data.csv'
hnames=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=pd.read_csv(filename,names=hnames)
array = dataframe.values
#seprate array into input and output components
X= array[: ,0:8] #[row ,cols]
Y= array[: ,8]
#feture extraction
test=SelectKBest(score_func=chi2,k=4)
fit=test.fit(X,Y)
#summarize scores
set_printoptions(precision=3)
print(fit.scores_)
features=fit.transform(X)
#summarize selected features
print("\n\n")
print(features[0:20,:])

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]



[[148.    0.   33.6  50. ]
 [ 85.    0.   26.6  31. ]
 [183.    0.   23.3  32. ]
 [ 89.   94.   28.1  21. ]
 [137.  168.   43.1  33. ]
 [116.    0.   25.6  30. ]
 [ 78.   88.   31.   26. ]
 [115.    0.   35.3  29. ]
 [197.  543.   30.5  53. ]
 [125.    0.    0.   54. ]
 [110.    0.   37.6  30. ]
 [168.    0.   38.   34. ]
 [139.    0.   27.1  57. ]
 [189.  846.   30.1  59. ]
 [166.  175.   25.8  51. ]
 [100.    0.   30.   32. ]
 [118.  230.   45.8  31. ]
 [107.    0.   29.6  31. ]
 [103.   83.   43.3  33. ]
 [115.   96.   34.6  32. ]]


In [3]:
#Feature Extraction with Recursive Feature Elimination(RFE)
import pandas as pd
from numpy import set_printoptions

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings("ignore")

#load data
filename='/home/diwakar/Downloads/IITK ML Data/indians-diabetes.data.csv'
hnames=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=pd.read_csv(filename,names=hnames)
array = dataframe.values
#seprate array into input and output components
X= array[: ,0:8] #[row ,cols]
Y= array[: ,8]
#feture extraction
model=LogisticRegression()
rfe=RFE(model,4)
fit=rfe.fit(X,Y)
result=fit.transform(X)
print("Number of Feature: ",fit.n_features_)
print("Selected Features: ",fit.support_)
print("Feature Ranking: ",fit.ranking_)
print("\n\n",result[:30,:])    


Number of Feature:  4
Selected Features:  [ True  True False False False  True  True False]
Feature Ranking:  [1 1 2 4 5 1 1 3]


 [[6.000e+00 1.480e+02 3.360e+01 6.270e-01]
 [1.000e+00 8.500e+01 2.660e+01 3.510e-01]
 [8.000e+00 1.830e+02 2.330e+01 6.720e-01]
 [1.000e+00 8.900e+01 2.810e+01 1.670e-01]
 [0.000e+00 1.370e+02 4.310e+01 2.288e+00]
 [5.000e+00 1.160e+02 2.560e+01 2.010e-01]
 [3.000e+00 7.800e+01 3.100e+01 2.480e-01]
 [1.000e+01 1.150e+02 3.530e+01 1.340e-01]
 [2.000e+00 1.970e+02 3.050e+01 1.580e-01]
 [8.000e+00 1.250e+02 0.000e+00 2.320e-01]
 [4.000e+00 1.100e+02 3.760e+01 1.910e-01]
 [1.000e+01 1.680e+02 3.800e+01 5.370e-01]
 [1.000e+01 1.390e+02 2.710e+01 1.441e+00]
 [1.000e+00 1.890e+02 3.010e+01 3.980e-01]
 [5.000e+00 1.660e+02 2.580e+01 5.870e-01]
 [7.000e+00 1.000e+02 3.000e+01 4.840e-01]
 [0.000e+00 1.180e+02 4.580e+01 5.510e-01]
 [7.000e+00 1.070e+02 2.960e+01 2.540e-01]
 [1.000e+00 1.030e+02 4.330e+01 1.830e-01]
 [1.000e+00 1.150e+02 3.460e+01 5.290e-01]
 [3.000e+