In [3]:
#Normalize data
from sklearn.preprocessing import Normalizer
from pandas import read_csv
from numpy import set_printoptions
filename='/home/diwakar/Downloads/IITK ML Data/indians-diabetes.data.csv'
hnames=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=read_csv(filename,names=hnames)
array = dataframe.values
print(array)
#seprate array into input and output components
X= array[: ,0:8] #[row ,cols]
Y= array[: ,8]
scaler=Normalizer()
normalizedX=scaler.fit_transform(X)
#summarize transformed data
set_printoptions(precision=2)
print(normalizedX[0:30, :])

[[  6.   148.    72.   ...   0.63  50.     1.  ]
 [  1.    85.    66.   ...   0.35  31.     0.  ]
 [  8.   183.    64.   ...   0.67  32.     1.  ]
 ...
 [  5.   121.    72.   ...   0.24  30.     0.  ]
 [  1.   126.    60.   ...   0.35  47.     1.  ]
 [  1.    93.    70.   ...   0.32  23.     0.  ]]
[[3.36e-02 8.28e-01 4.03e-01 1.96e-01 0.00e+00 1.88e-01 3.51e-03 2.80e-01]
 [8.42e-03 7.16e-01 5.56e-01 2.44e-01 0.00e+00 2.24e-01 2.96e-03 2.61e-01]
 [4.04e-02 9.24e-01 3.23e-01 0.00e+00 0.00e+00 1.18e-01 3.39e-03 1.62e-01]
 [6.61e-03 5.88e-01 4.36e-01 1.52e-01 6.22e-01 1.86e-01 1.10e-03 1.39e-01]
 [0.00e+00 5.96e-01 1.74e-01 1.52e-01 7.31e-01 1.88e-01 9.96e-03 1.44e-01]
 [3.49e-02 8.10e-01 5.17e-01 0.00e+00 0.00e+00 1.79e-01 1.40e-03 2.09e-01]
 [2.18e-02 5.66e-01 3.63e-01 2.32e-01 6.38e-01 2.25e-01 1.80e-03 1.89e-01]
 [8.06e-02 9.26e-01 0.00e+00 0.00e+00 0.00e+00 2.84e-01 1.08e-03 2.34e-01]
 [3.41e-03 3.36e-01 1.19e-01 7.67e-02 9.25e-01 5.20e-02 2.69e-04 9.03e-02]
 [4.80e-02 7.49e-01 5.76e