In [3]:
import pandas as pd
from numpy import set_printoptions
from sklearn.preprocessing import MinMaxScaler
filename='/home/diwakar/Downloads/IITK ML Data/indians-diabetes.data.csv'
hnames=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=pd.read_csv(filename,names=hnames)
array = dataframe.values
print(array)
#seprate array into input and output components
X= array[: ,0:8] #[row ,cols]
Y= array[: ,8]
scaler = MinMaxScaler(feature_range=(1,5))
#First Method
rescaledX=scaler.fit_transform(X)
#Second Method
rescaledX=scaler.transform(X)

#Summarize transformed data
set_printoptions(precision=2)
print(rescaledX [:30,: ] )  #[row,cols]


[[  6.   148.    72.   ...   0.63  50.     1.  ]
 [  1.    85.    66.   ...   0.35  31.     0.  ]
 [  8.   183.    64.   ...   0.67  32.     1.  ]
 ...
 [  5.   121.    72.   ...   0.24  30.     0.  ]
 [  1.   126.    60.   ...   0.35  47.     1.  ]
 [  1.    93.    70.   ...   0.32  23.     0.  ]]
[[2.41 3.97 3.36 2.41 1.   3.   1.94 2.93]
 [1.24 2.71 3.16 2.17 1.   2.59 1.47 1.67]
 [2.88 4.68 3.1  1.   1.   2.39 2.01 1.73]
 [1.24 2.79 3.16 1.93 1.44 2.68 1.15 1.  ]
 [1.   3.75 2.31 2.41 1.79 3.57 4.77 1.8 ]
 [2.18 3.33 3.43 1.   1.   2.53 1.21 1.6 ]
 [1.71 2.57 2.64 2.29 1.42 2.85 1.29 1.33]
 [3.35 3.31 1.   1.   1.   3.1  1.1  1.53]
 [1.47 4.96 3.3  2.82 3.57 2.82 1.14 3.13]
 [2.88 3.51 4.15 1.   1.   1.   1.26 3.2 ]
 [1.94 3.21 4.02 1.   1.   3.24 1.19 1.6 ]
 [3.35 4.38 3.43 1.   1.   3.27 1.78 1.87]
 [3.35 3.79 3.62 1.   1.   2.62 3.33 3.4 ]
 [1.24 4.8  2.97 1.93 5.   2.79 1.55 3.53]
 [2.18 4.34 3.36 1.77 1.83 2.54 1.87 3.  ]
 [2.65 3.01 1.   1.   1.   2.79 1.69 1.73]
 [1.   3.37 