In [7]:
#Feature Extraction with Principal Components Analysis (PCA)
import pandas as pd
# from numpy import set_printoptions
from sklearn.decomposition import PCA
import warnings
warnings.filterwarnings("ignore")

#load data
filename='/home/diwakar/Downloads/IITK ML Data/indians-diabetes.data.csv'
hnames=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=pd.read_csv(filename,names=hnames)
array = dataframe.values
#seprate array into input and output components
X= array[: ,0:8] #[row ,cols]
Y= array[: ,8]
#feture extraction
pca=PCA(n_components=3)
fit=pca.fit(X)
result=pca.transform(X)


print("\n\nresult \n",result)
#Summarize components

print("Explained Varience : ",fit.explained_variance_ratio_)



result 
 [[-75.71465491 -35.95078264  -7.26078895]
 [-82.3582676   28.90821322  -5.49667139]
 [-74.63064344 -67.90649647  19.46180812]
 ...
 [ 32.11319827   3.3766648   -1.58786446]
 [-80.21449431 -14.18601977  12.3512639 ]
 [-81.30814972  21.62149606  -8.15276833]]
Explained Varience :  [0.88854663 0.06159078 0.02579012]
