In [12]:
import numpy as np
from sklearn.preprocessing import Binarizer
X=np.array([[1.,-1.,2.],
           [2.,0.,0.],
           [0.,1.,-1.]])
transformer=Binarizer(threshold=1) #By default threshold is 0
print(transformer.transform(X))

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 0.]]
