In [15]:
list1=[1,2,3]
#list do not support operation broadcosting
print(list1[0]+list1[1])
a=list1[2]*list1[1]
print(a)
print(list1[2])
print("list1*4 = ",list1*4)

3
6
3
list1*4 =  [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [4]:
import numpy as np
nparr=np.array([1,2,3])
print(nparr)
print("nparr*4 = ",nparr*4)
print("nparr+4 = ",nparr+4)
print(nparr[2])

[1 2 3]
nparr*4 =  [ 4  8 12]
nparr+4 =  [5 6 7]
3


In [30]:
a=10
print(type(a))
a=12.5
print(type(a))
a='hello'

print(type(a))

import numpy as np
nparr=np.array([1,2.0,3])
print(type(nparr))

print("nparr.dtype",nparr.dtype)
print("nparr.shape",nparr.shape)
print("nparr.size",nparr.size)

<class 'int'>
<class 'float'>
<class 'str'>
<class 'numpy.ndarray'>
nparr.dtype float64
nparr.shape (3,)
nparr.size 3


In [32]:
import numpy as np
print("---------------------------------")
ddarr=np.array([[1,2,3],[4,5,6]])
print("ddarr.ndim = ",ddarr.ndim)
print("ddarr.shape = ",ddarr.shape)
#ddarr.shape=(2L,3L)
print("ddarr.size = ",ddarr.size)
print("len(ddarr) = ",len(ddarr))
print("ddarr.dtype = ",ddarr.dtype)
print(ddarr)
print('*************************************')
print("ddarr.[0,1] = ",ddarr[0,1]) #2 [row,column]
print("ddarr[0 ] = ",ddarr[0 ])
print("ddarr[:,0] = ",ddarr[:,0])
print("ddarr[1 ,:] = ",ddarr[1,:])

---------------------------------
ddarr.ndim =  2
ddarr.shape =  (2, 3)
ddarr.size =  6
len(ddarr) =  2
ddarr.dtype =  int64
[[1 2 3]
 [4 5 6]]
*************************************
ddarr.[0,1] =  2
ddarr[0 ] =  [1 2 3]
ddarr[:,0] =  [1 4]
ddarr[1 ,:] =  [4 5 6]


In [41]:
import numpy as np
d1=np.array([[1,2],
            [3,4],
            [5,6],
            [7,8],
            [9,10],
            [11,12],
            [13,14]])
print(d1)
print(d1.shape)
print(d1.ndim)
#Entire expression before "," is for rows
print("d1[ : :2, 0]",d1[ : :2, 0])
print('d1[1: :2,1]',d1[1: :2,1])
print("d1[::2]\n",d1[::2])
print(d1[1::2,1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]]
(7, 2)
2
d1[ : :2, 0] [ 1  5  9 13]
d1[1: :2,1] [ 4  8 12]
d1[::2]
 [[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[ 4  8 12]


In [45]:
import numpy as np
zr=np.zeros([3,4])
print("Zeros field array zr = \n",zr)

ar=np.ones([4,4])
print("1's field array ones = \n",ar)
print(ar*4)
print(ar.dtype)
zr2=np.zeros(5)
print("Zeros field array zr = \n",zr2)
print(zr2.shape)


Zeros field array zr = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
1's field array ones = 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
float64
Zeros field array zr = 
 [0. 0. 0. 0. 0.]
(5,)


In [53]:
import numpy as np
ar=np.arange(1,6) #[1,2,3,4,5]
print("ar = ",ar)
ar[3]=16
print("after updating, ar = ",ar)

ar =  [1 2 3 4 5]
after updating, ar =  [ 1  2  3 16  5]


In [63]:
import numpy as np
arr=np.array([11,22,33,0.,44,55])
print("arr.sum() = ",arr.sum())
print(np.sum(arr))
print("arr.std() = ",arr.std())
print("arr.min() = ",arr.min())
print(np.min(arr))
print(np.mean(arr))
print("arr.size = ",arr.size)
print(len(arr))
print("arr.shape = ",arr.shape)

arr.sum() =  165.0
165.0
arr.std() =  18.786076404259266
arr.min() =  0.0
0.0
27.5
arr.size =  6
6
arr.shape =  (6,)


In [73]:
import numpy as np
n1=np.array([4,5,6])
n2=np.array([1,2,3])
print("\n\n")
print("n1 = ",n1)
print("n2 = ",n2)
print("n1+n2 = ",n1+n2)
print("n1-n2 = ",n1-n2)
print("n1*n2 = ",n1*n2)
print("n1/n2 = ",n1/n2)
# n3=np.array([4,5,6,7])
# print(n1+n3)
n4=[2,6,5]

print(n1+n4)
print(type(n4))
print(type(n1))
print(type(n1+n4))




n1 =  [4 5 6]
n2 =  [1 2 3]
n1+n2 =  [5 7 9]
n1-n2 =  [3 3 3]
n1*n2 =  [ 4 10 18]
n1/n2 =  [4.  2.5 2. ]
[ 6 11 11]
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [78]:
import numpy as np
n4=np.array([10,-1,0,90,300,-6,2])
print("Before : ",n4)
print("\n\t",sorted(n4)) #external sorting
print("After : ",n4)
n4.sort() #In-place sorting(internal sorting)
print("After n4.sort() = ",n4)

Before :  [ 10  -1   0  90 300  -6   2]

	 [-6, -1, 0, 2, 10, 90, 300]
After :  [ 10  -1   0  90 300  -6   2]
After n4.sort() =  [ -6  -1   0   2  10  90 300]


In [80]:
import numpy as np
n4=np.array([777,555,222,111,999,666])
print("n4 = : ",n4)
print("n4.argsort(): ",n4.argsort()) #[3,2,1,5,0,4]
indexArr=n4.argsort()
print(n4)
print("Min=",n4[indexArr[0]])
print(n4[indexArr[len(indexArr)-1]])


n4 = :  [777 555 222 111 999 666]
n4.argsort():  [3 2 1 5 0 4]
[777 555 222 111 999 666]
Min= 111
999


In [83]:
import numpy as np
print(np.pi)
print(np.linspace(-5,5,11))
print(np.linspace(-np.pi,np.pi,256))

3.141592653589793
[-5. -4. -3. -2. -1.  0.  1.  2.  3.  4.  5.]
[-3.14159265 -3.11695271 -3.09231277 -3.06767283 -3.04303288 -3.01839294
 -2.993753   -2.96911306 -2.94447311 -2.91983317 -2.89519323 -2.87055329
 -2.84591335 -2.8212734  -2.79663346 -2.77199352 -2.74735358 -2.72271363
 -2.69807369 -2.67343375 -2.64879381 -2.62415386 -2.59951392 -2.57487398
 -2.55023404 -2.52559409 -2.50095415 -2.47631421 -2.45167427 -2.42703432
 -2.40239438 -2.37775444 -2.3531145  -2.32847456 -2.30383461 -2.27919467
 -2.25455473 -2.22991479 -2.20527484 -2.1806349  -2.15599496 -2.13135502
 -2.10671507 -2.08207513 -2.05743519 -2.03279525 -2.0081553  -1.98351536
 -1.95887542 -1.93423548 -1.90959553 -1.88495559 -1.86031565 -1.83567571
 -1.81103577 -1.78639582 -1.76175588 -1.73711594 -1.712476   -1.68783605
 -1.66319611 -1.63855617 -1.61391623 -1.58927628 -1.56463634 -1.5399964
 -1.51535646 -1.49071651 -1.46607657 -1.44143663 -1.41679669 -1.39215674
 -1.3675168  -1.34287686 -1.31823692 -1.29359698 -1.26895703 

In [93]:
import numpy as np
print("--Transcendental functions:---")
a=np.arange(1,6)
print(a)
print(np.sin(a))
print(np.log(a))
print(np.exp(a))

print(np.tan(90))

--Transcendental functions:---
[1 2 3 4 5]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
-1.995200412208242


In [96]:
import numpy as np
print("---Sum by rows and by columns:---")
x=np.array([[1,2],[3,4]])
print("x = \n",x)
#array([1,2],
#      [3,4])
print(x.sum())
print(x.sum(axis=0)) #columns(first dimension)
#array([4,6])
print(x[:,0].sum(),x[:1].sum()) #4, 6
print(x[:,0].sum(),x[:,1].sum()) #4, 6
print(x.sum(axis=1)) #rows(second dimension) 3, 7
print(x[0,:].sum(),x[1,:].sum())# 3,7    

---Sum by rows and by columns:---
x = 
 [[1 2]
 [3 4]]
10
[4 6]
4 3
4 6
[3 7]
3 7
