In [3]:
import numpy as np
from sklearn.preprocessing import Normalizer
X=np.array([[4,1,2,2],[1,3,9,3],[5,7,5,1]])
transformer =Normalizer().fit(X) #fit does nothing.
print(transformer.transform(X))

[[0.8 0.2 0.4 0.4]
 [0.1 0.3 0.9 0.3]
 [0.5 0.7 0.5 0.1]]
