In [4]:
#Feature Extraction with Recursive Feature Elimination(RFE)
import pandas as pd
from numpy import set_printoptions

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings("ignore")

#load data
filename='/home/diwakar/Downloads/IITK ML Data/indians-diabetes.data.csv'
hnames=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=pd.read_csv(filename,names=hnames)
array = dataframe.values
#seprate array into input and output components
X= array[: ,0:8] #[row ,cols]
Y= array[: ,8]
#feture extraction
model=LogisticRegression()
rfe=RFE(model,3)
fit=rfe.fit(X,Y)
result=fit.transform(X)
print("Number of Feature: ",fit.n_features_)
print("Selected Features: ",fit.support_)
print("Feature Ranking: ",fit.ranking_)
print("\n\n",result[:30,:])    


Number of Feature:  3
Selected Features:  [ True False False False False  True  True False]
Feature Ranking:  [1 2 3 5 6 1 1 4]


 [[ 6.    33.6    0.627]
 [ 1.    26.6    0.351]
 [ 8.    23.3    0.672]
 [ 1.    28.1    0.167]
 [ 0.    43.1    2.288]
 [ 5.    25.6    0.201]
 [ 3.    31.     0.248]
 [10.    35.3    0.134]
 [ 2.    30.5    0.158]
 [ 8.     0.     0.232]
 [ 4.    37.6    0.191]
 [10.    38.     0.537]
 [10.    27.1    1.441]
 [ 1.    30.1    0.398]
 [ 5.    25.8    0.587]
 [ 7.    30.     0.484]
 [ 0.    45.8    0.551]
 [ 7.    29.6    0.254]
 [ 1.    43.3    0.183]
 [ 1.    34.6    0.529]
 [ 3.    39.3    0.704]
 [ 8.    35.4    0.388]
 [ 7.    39.8    0.451]
 [ 9.    29.     0.263]
 [11.    36.6    0.254]
 [10.    31.1    0.205]
 [ 7.    39.4    0.257]
 [ 1.    23.2    0.487]
 [13.    22.2    0.245]
 [ 5.    34.1    0.337]]


In [5]:
#Feature Extraction with Recursive Feature Elimination(RFE)
import pandas as pd
from numpy import set_printoptions

from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import warnings
warnings.filterwarnings("ignore")

#load data
filename='/home/diwakar/Downloads/IITK ML Data/indians-diabetes.data.csv'
hnames=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=pd.read_csv(filename,names=hnames)
array = dataframe.values
#seprate array into input and output components
X= array[: ,0:8] #[row ,cols]
Y= array[: ,8]
#feture extraction
model=LogisticRegression()
rfe=RFE(model,4)
fit=rfe.fit(X,Y)
result=fit.transform(X)
print("Number of Feature: ",fit.n_features_)
print("Selected Features: ",fit.support_)
print("Feature Ranking: ",fit.ranking_)
print("\n\n",result[:30,:])    


Number of Feature:  4
Selected Features:  [ True  True False False False  True  True False]
Feature Ranking:  [1 1 2 4 5 1 1 3]


 [[6.000e+00 1.480e+02 3.360e+01 6.270e-01]
 [1.000e+00 8.500e+01 2.660e+01 3.510e-01]
 [8.000e+00 1.830e+02 2.330e+01 6.720e-01]
 [1.000e+00 8.900e+01 2.810e+01 1.670e-01]
 [0.000e+00 1.370e+02 4.310e+01 2.288e+00]
 [5.000e+00 1.160e+02 2.560e+01 2.010e-01]
 [3.000e+00 7.800e+01 3.100e+01 2.480e-01]
 [1.000e+01 1.150e+02 3.530e+01 1.340e-01]
 [2.000e+00 1.970e+02 3.050e+01 1.580e-01]
 [8.000e+00 1.250e+02 0.000e+00 2.320e-01]
 [4.000e+00 1.100e+02 3.760e+01 1.910e-01]
 [1.000e+01 1.680e+02 3.800e+01 5.370e-01]
 [1.000e+01 1.390e+02 2.710e+01 1.441e+00]
 [1.000e+00 1.890e+02 3.010e+01 3.980e-01]
 [5.000e+00 1.660e+02 2.580e+01 5.870e-01]
 [7.000e+00 1.000e+02 3.000e+01 4.840e-01]
 [0.000e+00 1.180e+02 4.580e+01 5.510e-01]
 [7.000e+00 1.070e+02 2.960e+01 2.540e-01]
 [1.000e+00 1.030e+02 4.330e+01 1.830e-01]
 [1.000e+00 1.150e+02 3.460e+01 5.290e-01]
 [3.000e+